// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InsertPostController from "./insert_post_controller"
application.register("insert-post", InsertPostController)

import LikeWithoutReloadController from "./like_without_reload_controller"
application.register("like-without-reload", LikeWithoutReloadController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)
